require: rubocop-rails
Rails:
  Enabled: true
AllCops:
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - '**/db/schema.rb'
    - '**/vendor/bundle/**/*'
    - '**/node_modules/**/*'

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
  Exclude:
    - '**/db/migrate/**/*'
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - '**/spec/**/*'
    - '**/db/migrate/**/*'
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/RescueEnsureAlignment:
  Enabled: false
Layout/LineLength:
  Max: 150
  IgnoredPatterns:
    - '^\W*\#'

Style/ClassAndModuleChildren:
  Exclude:
    - '**/app/controllers/**/*'
Style/Documentation:
  Exclude:
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
Style/DocumentationMethod:
  Enabled: true
  RequireForNonPublicMethods: true
  Exclude:
    - '**/db/migrate/**/*'
    - '**/bin/**/*'
    - '**/lib/engines/*/bin/**/*'
    - '**/spec/**/*'
    - '**/doc-src/**/*'
Style/DoubleNegation:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/AccessModifierDeclarations:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/*.rake'
    - '**/config/routes.rb'
Metrics/MethodLength:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/ModuleLength:
  Exclude:
    - '**/spec/**/*'

Rails/Blank:
  UnlessPresent: false
Rails/HasAndBelongsToMany:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
Rails/FilePath:
  EnforcedStyle: arguments
