Rails:
  Enabled: true
Metrics/LineLength:
  Max: 150
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
Layout/IndentationConsistency:
  EnforcedStyle: rails
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Rails/Blank:
  UnlessPresent: false