Rails:
  Enabled: true
AllCops:
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'

Layout/IndentationConsistency:
  EnforcedStyle: rails
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - indented
    - indented_relative_to_receiver
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special
  Exclude:
    - 'db/migrate/**/*'
Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special
Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*'
    - 'db/migrate/**/*'
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
Style/Documentation:
  Exclude:
    - 'db/migrate/**/*'
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'
Metrics/LineLength:
  Max: 150
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Rails/Blank:
  UnlessPresent: false